### ISSUE TITLE
Test dependencies put in BUILD_REQUIRES when generating MYMETA.*

### ISSUE THREAD

**Issue by Grinnz** [rsrchboy/net-amazon-signature-v3#1]
Although META.json (generated by dzil) correctly identifies Test::Moose::More and other test dependencies (https://metacpan.org/source/RSRCHBOY/Net-Amazon-Signature-V3-0.001/META.json#L22-59), Makefile.PL (also seemingly generated by dzil, but not indicated as such) puts them unconditionally in BUILD_REQUIRES for generating MYMETA.json (https://metacpan.org/source/RSRCHBOY/Net-Amazon-Signature-V3-0.001/Makefile.PL#L14-22), which causes cpan installers to install them even when not running the test phase. Maybe just regenerating the dist with a new Makefile.PL based on new versions of dzil and an updated MakeMaker plugin would be sufficient to fix this.

**Comment by Grinnz** [comment]
Hi, any chance this can be looked at? If you want to give me comaint permissions on the distribution (cpanid: DBOOK) I would be happy to do a maintenance release with no code changes to attempt to fix this issue.

**Comment by rsrchboy** [comment]
So, I started taking a look at this and it turns out that a simple rebuild of the dist doesn't do the trick.  I'm looking a bit closer into why `Dist::Zilla::Plugin::AutoPrereqs` wants these in the `build_requires` section; perhaps there's a bit I could flip.

Thanks for the ping :)

**Comment by Grinnz** [comment]
If I do a local `dzil build` the generated Makefile.PL looks correct: https://paste.fedoraproject.org/paste/V3ztOqMAow18uMqlNv-xdQ/raw

**Comment by rsrchboy** [comment]
Ugh, you're correct.  I was looking at the `META.yml` believing that the information therein would be the same as that contained in `Makefile.PL` (and `META.json`, for that matter).

Rebuilding and releasing now.

**Comment by Grinnz** [comment]
Thanks!

**Comment by karenetheridge** [comment]
META.json uses meta-spec version 2. META.yml uses meta-spec version 1.4.
